### ISSUE TITLE
Using external ZooKeeper instance

### ISSUE THREAD

**Issue by ivangreene** [elkozmon/zoonavigator#40]
If wanting to connect to a local ZooKeeper on 2181 outside of the docker container, we cannot use network: host mode. Here is how I was able to get around this, remove net=host mode and open 9000 on the host machine:

```
docker run \
  -d -p 9000:9000 \
  --name zoonavigator \
  --restart unless-stopped \
  elkozmon/zoonavigator:latest
```

And use the connection string `docker.for.mac.host.internal:2181` (varies by operating system, see this answer: https://stackoverflow.com/a/43541732/7983959

Wanted to share here in case others experience this issue, it was not straightforward to determine the issue

**Comment by elkozmon** [comment]
Thanks for sharing this, I will probably link this issue in the docs too.

**Comment by solarmosaic-kflorence** [comment]
This configuration worked for me when deploying to local Kubernetes with `docker stack deploy`:

```yaml
    image: bitnami/zookeeper:latest
    hostname: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - zookeeper1-data:/bitnami/zookeeper
  zoonavigator:
    image: elkozmon/zoonavigator:0.7.1
    ports:
      - "8000:8000"
    environment:
      HTTP_PORT: 8000
      AUTO_CONNECT_CONNECTION_STRING: zookeeper1:2181

volumes:
  zookeeper1-data:
```
