### ISSUE TITLE
Error: Unable to establish connection with ZooKeeper

### ISSUE THREAD

**Issue by UTGuy** [elkozmon/zoonavigator#49]
Connecting with the docker-compose name does not work here but connecting with the network IP does. In my sample application, I had the name as simply 'zookeeper' instead of 'compliance-message-queue-zookeeper' and connected with 'zookeeper:2181' and it worked. Is there a name length issue somewhere?

![image](https://user-images.githubusercontent.com/1872858/81694045-d6b7d600-942e-11ea-8e7b-36146f96ea4c.png)

![image](https://user-images.githubusercontent.com/1872858/81694009-c7d12380-942e-11ea-8068-955d24d3ccb3.png)

**Comment by elkozmon** [comment]
Hi. 

It seems unlikely that name length would be the issue, but tbh, I have no idea.

Is it possible for you to post your Docker compose file for me to try it out?

Thanks

**Comment by UTGuy** [comment]
```
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

    version: '3.5'
    services:
      compliance-message-queue-zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
          - 9100:8080
        networks:
          - proxynet

      compliance-message-queue-zookeeper-ui:
        image: elkozmon/zoonavigator
        ports:
          - 9101:9000
        environment: 
          CONNECTION_LOCALZK_NAME: compliance-message-queue
          CONNECTION_LOCALZK_CONN: compliance-message-queue-zookeeper:2181
          AUTO_CONNECT_CONNECTION_ID: LOCALZK
        networks:
          - proxynet

      compliance-message-queue-kafka-ui:
        image: digitsy/kafka-magic
        ports:
          - 9102:80
        environment: 
          KMAGIC_ALLOW_TOPIC_DELETE: "true"
          CONFIG_STORE_TYPE: "file"
          CONFIG_STORE_CONNECTION: "Data Source=KafkaMagicConfig.db;"
        networks:
          - proxynet
          
      compliance-message-queue-kafka-1:
        image: bitnami/kafka
        ports:
          - "9095:9092"
        environment:
          ALLOW_PLAINTEXT_LISTENER: 'yes'
          KAFKA_ZOOKEEPER_CONNECT: compliance-message-queue-zookeeper:2181
          KAFKA_BROKER_ID: 500
          KAFKA_offsets_topic_replication_factor: 1
        volumes:
          - ./volumes/kafka/docker.sock:/var/run/docker.sock
          - ./volumes/kafka/data/500:/kafka
        networks:
          - proxynet

    networks:
      proxynet:
        name: content_config_tool_network
```
