### ISSUE TITLE
docker-compose.yaml

### ISSUE THREAD

**Issue by yingzhuo** [elkozmon/zoonavigator#66]
I love the navigator. Thanks.

Maybe a `docker-compose.yml` can help some docker-compose' fans (like me).

```yaml
version: "3.9"

services:
  zookeeper-navi:
    image: "elkozmon/zoonavigator:latest"
    restart: unless-stopped
    container_name: "zoonavigator"
    network_mode: "host"
    environment:
      - "HTTP_PORT=9090"
```

How about include my shit to README.md ? 

Thank you again.
