### ISSUE TITLE
"Malformed Authorization header" with nginx Basic-Auth

### ISSUE THREAD

**Issue by The-Judge** [elkozmon/zoonavigator#74]
As your [FAQ](https://zoonavigator.elkozmon.com/en/latest/faqs.html#how-to-enable-basic-authentication) suggests, I use nginx (Docker image [nginxproxy/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy)) to Basic-Auth Zoonavigator.
After successfully implementing this, Zoonavigator states "Malformed Authorization header" Error when logging into Zookeeper instances:

![Error](https://i.ibb.co/b5kzYqw/Screenshot-2021-09-10-at-13-14-55.png)

**Comment by elkozmon** [comment]
Thanks for reporting this. I will look into it in a couple of days and will get back to you (I'm traveling at the moment).
________________________________
From: Marc Richter ***@***.***>
Sent: Friday, September 10, 2021 12:19 PM
To: elkozmon/zoonavigator
Cc: Subscribed
Subject: [elkozmon/zoonavigator] "Malformed Authorization header" with nginx Basic-Auth (#74)


As your FAQ<https://zoonavigator.elkozmon.com/en/latest/faqs.html#how-to-enable-basic-authentication> suggests, I use nginx (Docker image nginxproxy/nginx-proxy<https://github.com/nginx-proxy/nginx-proxy>) to Basic-Auth Zoonavigator.
After successfully implementing this, Zoonavigator states "Malformed Authorization header" Error when logging into Zookeeper instances:

[Error]<https://camo.githubusercontent.com/e6c7215ddef9cf24b275972dbdca048cc15ba4b2fd25bc7ebf8e42c17b24d6b1/68747470733a2f2f692e6962622e636f2f62356b7a5971772f53637265656e73686f742d323032312d30392d31302d61742d31332d31342d35352e706e67>

**Comment by The-Judge** [comment]
Sure - just let me know in case you need any details. In the meantime, I'll try to provide meaningful info best-efford-wise:

This is my docker-compose.yml:

```
---
version: '2'
services:
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    hostname: zoonavigator
    container_name: zoonavigator
    restart: unless-stopped
    ports:
      - 9000
    environment:
      HTTP_PORT: 9000
      VIRTUAL_HOST: deb11zk03.zen-net.de
      VIRTUAL_PORT: 9000
      CONNECTION_DEFAULT_CONN: 172.28.128.40:2181,172.28.128.42:2181,172.28.128.41:2181
      CONNECTION_DEFAULT_NAME: Zen-Net DEV

  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/virtual_host_htpasswds:/etc/nginx/htpasswd:ro
    environment:
      ENABLE_IPV6: 'true'
      DEFAULT_HOST: deb11zk03.zen-net.de
```

The `nginxproxy/nginx-proxy`-Image picks up files from `/etc/nginx/htpasswd`, which are named like the `${VIRTUAL_HOST}`-Variable of the to-be-proxied - hosts, which is `deb11zk03.zen-net.de` in this case. So I added a htaccess - file at `/etc/nginx/virtual_host_htpasswds/deb11zk03.zen-net.de` on the Docker host, which ends up as `/etc/nginx/htpasswd/deb11zk03.zen-net.de` in the container.

With that, Basic auth works, but leads to the shown error in Zoonavigator.
