### ISSUE TITLE
Zookeeper 3.7 test succeeded (docker compose)

### ISSUE THREAD

**Issue by duee** [elkozmon/zoonavigator#77]
version: zookeeper 3.7
Cluster info :
zk1
zk2
zk3 （leader）
network  info：
![image](https://user-images.githubusercontent.com/11386482/145252912-c43cfc4a-b6e4-4ec6-98b3-d963f04b4a50.png)

docker-compose.yml
```
version: "3.7"

networks:
   zk-net:
     external: true

services:
  zookeeper:
    image: "elkozmon/zoonavigator:latest"
    ports:
      - 9090:9090
    restart: always
    container_name: "zoonavigator"
    networks:
        - zk-net
    environment:
      - "HTTP_PORT=9090"
      - "CONNECTION_LOCALZK_NAME=zk-net"
      - "CONNECTION_LOCALZK_CONN=zk3"
```

Please note that "connection_localzk_conn = zk3" is because I am on the same network.
