### ISSUE TITLE
Zookeeper 3.9.3 test succeeded (docker compose)

### ISSUE THREAD

**Issue by drawsta** [elkozmon/zoonavigator#91]
```yaml
version: "3.9"
services:
    zookeeper:
        image: zookeeper:3.9.3
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
            - ZOO_SERVER_ID=1
            - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
        networks:
            - zk-network
        restart: always
    zoonavigator:
        image: elkozmon/zoonavigator:1.1.3
        container_name: zoonavigator
        ports:
            - 9000:9000
        environment:
            - HTTP_PORT=9000
            - CONNECTION_LOCALZK_CONN=zookeeper:2181
        depends_on:
            - zookeeper
        networks:
            - zk-network
        restart: unless-stopped
networks:
    zk-network:
        driver: bridge
```
